import React from 'react';
import { RefreshCw, BarChart3, AlertCircle, Map, CheckCircle2, PlayCircle, Lock, Layout, Terminal, Cloud, Database, FileCode, Search, Share2, Info, Layers } from 'lucide-react';

const Dashboard = () => {
  return (
    <div className="skill-dashboard">
      <header className="dash-header-v2">
        <div>
          <h1 style={{ fontSize: '2.5rem', fontWeight: '800', marginBottom: '0.5rem' }}>Skill Dashboard</h1>
          <p style={{ color: '#9ca3af', fontSize: '1rem' }}>AI-powered analysis of your technical profile & career trajectory</p>
        </div>
        <button className="btn-resync">
           <RefreshCw size={16} /> Re-sync Profile
        </button>
      </header>

      <div className="dash-grid" style={{ gap: '2rem' }}>
        {/* Extracted Skills Card */}
        <div className="glass-card" style={{ padding: '2rem' }}>
          <div className="card-header">
            <h3><BarChart3 size={20} color="var(--accent-purple)" /> Extracted Skills</h3>
            <span className="badge-small">12 TOTAL</span>
          </div>
          
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))', gap: '1rem' }}>
            {[
              { name: 'React.js', level: 'EXPERT', icon: <Layout size={18} /> },
              { name: 'Python', level: 'INTERMEDIATE', icon: <Terminal size={18} /> },
              { name: 'AWS', level: 'BEGINNER', icon: <Cloud size={18} /> },
              { name: 'PostgreSQL', level: 'INTERMEDIATE', icon: <Database size={18} /> },
              { name: 'TypeScript', level: 'EXPERT', icon: <FileCode size={18} /> }
            ].map(skill => (
              <div key={skill.name} className="skill-chip-v2">
                <div className="skill-icon-box">{skill.icon}</div>
                <div className="skill-info-v2">
                  <span className="skill-name-v2">{skill.name}</span>
                  <span className="skill-level-v2">{skill.level}</span>
                </div>
              </div>
            ))}
          </div>

          <p style={{ marginTop: '3rem', fontSize: '0.75rem', color: '#6b7280', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
             <Info size={14} /> Analysis based on LinkedIn, GitHub, and Resume upload
          </p>
        </div>

        {/* Skill Gap Analysis Card */}
        <div className="glass-card" style={{ padding: '2rem' }}>
           <div className="card-header">
             <h3><AlertCircle size={20} color="#f59e0b" /> Skill Gap Analysis</h3>
             <span className="badge-small">PRIORITY GAPS</span>
           </div>

           <div className="gap-list-v2">
              {[
                { name: 'Kubernetes', role: 'Required for Senior DevOps roles', match: '98% Match Gap', priority: 'CRITICAL', icon: <Cloud size={18} /> },
                { name: 'Terraform', role: 'Missing in infrastructure layer', match: '85% Match Gap', priority: 'HIGH', icon: <Layers size={18} /> },
                { name: 'OAuth 2.0', role: 'Security implementation protocols', match: '72% Match Gap', priority: 'MEDIUM', icon: <Lock size={18} /> }
              ].map(gap => (
                <div key={gap.name} className="gap-item-v2">
                  <div className="gap-left">
                    <div className="skill-icon-box" style={{ background: 'rgba(245, 158, 11, 0.1)', color: '#f59e0b' }}>
                        {gap.icon}
                    </div>
                    <div className="gap-details">
                       <h4>{gap.name}</h4>
                       <p>{gap.role}</p>
                    </div>
                  </div>
                  <div className="gap-right">
                    <div className="gap-match">{gap.match}</div>
                    <div className="gap-priority-label">{gap.priority}</div>
                  </div>
                </div>
              ))}
           </div>
        </div>
      </div>

      {/* Learning Path Section */}
      <div className="roadmap-card-v2">
         <div className="roadmap-header">
           <div>
             <h3 style={{ fontSize: '1.75rem', fontWeight: '800', display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
                <Map size={24} color="var(--accent-purple)" /> Learning Path: Cloud Architect
             </h3>
             <p style={{ color: '#9ca3af', fontSize: '0.9rem' }}>Personalized roadmap generated by AI Copilot</p>
           </div>
           
           <div className="completion-box">
              <div style={{ textAlign: 'right' }}>
                <p style={{ fontSize: '0.85rem', fontWeight: '700', marginBottom: '0.5rem' }}>Completion: 15%</p>
                <div style={{ width: '120px', height: '6px', background: 'rgba(255,255,255,0.05)', borderRadius: '3px', overflow: 'hidden' }}>
                   <div style={{ width: '15%', height: '100%', background: 'var(--accent-purple)' }}></div>
                </div>
              </div>
              <div className="skill-icon-box" style={{ borderRadius: '50%', cursor: 'pointer' }}>
                <Share2 size={16} />
              </div>
           </div>
         </div>

         <div className="timeline-v2">
           {/* Module 01 */}
           <div className="timeline-node-v2">
              <div className="node-bullet completed"><CheckCircle2 size={18} /></div>
              <div className="timeline-card-v2">
                 <div className="node-content-v2">
                    <span style={{ fontSize: '0.7rem', fontWeight: '800', color: '#9ca3af', letterSpacing: '0.1em' }}>MODULE 01</span>
                    <span className="badge-small" style={{ marginLeft: '1rem', color: '#10b981', background: 'rgba(16, 185, 129, 0.1)' }}>COMPLETED</span>
                    <h4>Foundational Core Concepts</h4>
                    <div className="node-meta-v2">
                      <span>🕒 2 hours</span>
                      <span style={{ color: '#7f0df2' }}>⭐ High Priority</span>
                    </div>
                 </div>
                 <button style={{ background: 'none', border: 'none', color: '#7f0df2', fontWeight: '700', fontSize: '0.85rem', cursor: 'pointer' }}>
                   View Summary →
                 </button>
              </div>
           </div>

           {/* Module 02 */}
           <div className="timeline-node-v2">
              <div className="node-bullet active"></div>
              <div className="timeline-card-v2" style={{ border: '1px solid #7f0df2' }}>
                 <div className="node-content-v2">
                    <span style={{ fontSize: '0.7rem', fontWeight: '800', color: '#9ca3af', letterSpacing: '0.1em' }}>MODULE 02</span>
                    <span className="badge-small" style={{ marginLeft: '1rem', color: '#7f0df2', background: 'rgba(127, 13, 242, 0.1)' }}>IN PROGRESS</span>
                    <h4>Advanced Cloud Architectures</h4>
                    <div className="node-meta-v2">
                      <span>🕒 4.5 hours</span>
                      <span style={{ color: '#ef4444' }}>❗ Critical Priority</span>
                    </div>
                 </div>
                 <button className="btn-resync" style={{ fontSize: '0.8rem', padding: '0.6rem 1.2rem' }}>
                    <PlayCircle size={14} /> Resume Learning
                 </button>
              </div>
           </div>

           {/* Module 03 */}
           <div className="timeline-node-v2">
              <div className="node-bullet"><Lock size={16} color="#6b7280" /></div>
              <div className="timeline-card-v2 locked">
                 <div className="node-content-v2">
                    <span style={{ fontSize: '0.7rem', fontWeight: '800', color: '#9ca3af', letterSpacing: '0.1em' }}>MODULE 03</span>
                    <span className="badge-small" style={{ marginLeft: '1rem' }}>LOCKED</span>
                    <h4>Scalability & Optimization</h4>
                    <div className="node-meta-v2">
                      <span>🕒 3 hours</span>
                      <span>⚖️ Medium Priority</span>
                    </div>
                 </div>
              </div>
           </div>
         </div>
      </div>
    </div>
  );
};

export default Dashboard;
